/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthVerifyPendingRouteImport } from './routes/auth.verify-pending'
import { Route as AuthResetConfirmRouteImport } from './routes/auth.reset-confirm'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSuitesRouteImport } from './routes/_app.suites'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRunsRouteImport } from './routes/_app.runs'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRegressionRouteImport } from './routes/_app.regression'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppGenerateRouteImport } from './routes/_app.generate'
import { Route as AppBugsRouteImport } from './routes/_app.bugs'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyPendingRoute = AuthVerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetConfirmRoute = AuthResetConfirmRouteImport.update({
  id: '/reset-confirm',
  path: '/reset-confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppSuitesRoute = AppSuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegressionRoute = AppRegressionRouteImport.update({
  id: '/regression',
  path: '/regression',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppBugsRoute = AppBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/bugs': typeof AppBugsRoute
  '/generate': typeof AppGenerateRoute
  '/help': typeof AppHelpRoute
  '/integrations': typeof AppIntegrationsRoute
  '/planner': typeof AppPlannerRoute
  '/projects': typeof AppProjectsRoute
  '/regression': typeof AppRegressionRoute
  '/reports': typeof AppReportsRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/suites': typeof AppSuitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-confirm': typeof AuthResetConfirmRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/bugs': typeof AppBugsRoute
  '/generate': typeof AppGenerateRoute
  '/help': typeof AppHelpRoute
  '/integrations': typeof AppIntegrationsRoute
  '/planner': typeof AppPlannerRoute
  '/projects': typeof AppProjectsRoute
  '/regression': typeof AppRegressionRoute
  '/reports': typeof AppReportsRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/suites': typeof AppSuitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-confirm': typeof AuthResetConfirmRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/bugs': typeof AppBugsRoute
  '/_app/generate': typeof AppGenerateRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/regression': typeof AppRegressionRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/runs': typeof AppRunsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suites': typeof AppSuitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-confirm': typeof AuthResetConfirmRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/analytics'
    | '/bugs'
    | '/generate'
    | '/help'
    | '/integrations'
    | '/planner'
    | '/projects'
    | '/regression'
    | '/reports'
    | '/runs'
    | '/settings'
    | '/suites'
    | '/auth/callback'
    | '/auth/reset'
    | '/auth/reset-confirm'
    | '/auth/verify-pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/analytics'
    | '/bugs'
    | '/generate'
    | '/help'
    | '/integrations'
    | '/planner'
    | '/projects'
    | '/regression'
    | '/reports'
    | '/runs'
    | '/settings'
    | '/suites'
    | '/auth/callback'
    | '/auth/reset'
    | '/auth/reset-confirm'
    | '/auth/verify-pending'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/_app/analytics'
    | '/_app/bugs'
    | '/_app/generate'
    | '/_app/help'
    | '/_app/integrations'
    | '/_app/planner'
    | '/_app/projects'
    | '/_app/regression'
    | '/_app/reports'
    | '/_app/runs'
    | '/_app/settings'
    | '/_app/suites'
    | '/auth/callback'
    | '/auth/reset'
    | '/auth/reset-confirm'
    | '/auth/verify-pending'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-pending': {
      id: '/auth/verify-pending'
      path: '/verify-pending'
      fullPath: '/auth/verify-pending'
      preLoaderRoute: typeof AuthVerifyPendingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-confirm': {
      id: '/auth/reset-confirm'
      path: '/reset-confirm'
      fullPath: '/auth/reset-confirm'
      preLoaderRoute: typeof AuthResetConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/suites': {
      id: '/_app/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof AppSuitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regression': {
      id: '/_app/regression'
      path: '/regression'
      fullPath: '/regression'
      preLoaderRoute: typeof AppRegressionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generate': {
      id: '/_app/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bugs': {
      id: '/_app/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof AppBugsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBugsRoute: typeof AppBugsRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppHelpRoute: typeof AppHelpRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRegressionRoute: typeof AppRegressionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuitesRoute: typeof AppSuitesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBugsRoute: AppBugsRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppHelpRoute: AppHelpRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRegressionRoute: AppRegressionRoute,
  AppReportsRoute: AppReportsRoute,
  AppRunsRoute: AppRunsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuitesRoute: AppSuitesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthResetConfirmRoute: typeof AuthResetConfirmRoute
  AuthVerifyPendingRoute: typeof AuthVerifyPendingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
  AuthResetConfirmRoute: AuthResetConfirmRoute,
  AuthVerifyPendingRoute: AuthVerifyPendingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
